### ISSUE TITLE
ScanCapture format for IMU info

### ISSUE THREAD

**Issue by tianyilim** [microsoft/lamar-benchmark#74]
Hello, I'd like to convert the Captures recorded ScanCapture app into a rosbag. For example, the sequences in `LAMAR/raw/...ios_*`

I would like to better understand the IMU format specified in the [ScanCapture data format](https://github.com/microsoft/lamar-benchmark/tree/main/apps/ScanCapture_iOS#data-format):

Specifically, for the `accelerometer.txt` and `gyroscope.txt`:
- What frame are these measurements in? If in IMU frame, where can I find the cam-to-IMU transform?
- What units are `accelerometer.txt` in? Is it in m/s or g?

**Comment by sarlinpe** [comment]
The measurements are provided in g: https://developer.apple.com/documentation/coremotion/cmacceleration As for the cam-to-IMU transform, the rotation is identity (see [Figure 1](https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events#overview)) but the relative translation is unfortunately unknown. To estimate it, you could record some data and run [kalibr](https://github.com/ethz-asl/kalibr), as done here: https://tomas789.medium.com/iphone-calibration-camera-imu-and-kalibr-33b8645fb0aa This can also give you the intrinsic parameters of the IMU, which are also unknown.

**Comment by tianyilim** [comment]
Thanks a lot!

**Comment by tianyilim** [comment]
Hello, if anyone else is undertaking this, the link https://tomas789.medium.com/iphone-calibration-camera-imu-and-kalibr-33b8645fb0aa here is very helpful.

Another crucial step is, when converting the iPad IMU readings to ROS, it's important to **invert the value of the x axis**. I guess this is some difference in left/right coordinate systems.

For instance (a snippet of code used to write `imu.csv` as per Kalibr):
```python
for i in range(min_num_samples):
    timestamp = accel_data[i][0] * 1000  # to ns
    ax = -accel_data[i][1] * 9.81        # to m/s^2
    ay = +accel_data[i][2] * 9.81
    az = +accel_data[i][3] * 9.81
    rx = +gyro_data[i][1]
    ry = -gyro_data[i][2]
    rz = -gyro_data[i][3]

    writer.writerow([timestamp, rx, ry, rz, ax, ay, az])
```

From this, one can recover the identity rotation from cam to IMU as described by Paul.

If anyone is interested, my Kalibr results are:
```yaml
cam0:
  T_cam_imu:
  - [0.9999580564037295, 0.006751730699743652, -0.006188664301298458, -0.05172264695460033]
  - [-0.006633743346060444, 0.9997995354134769, 0.018891332303855472, 0.06306196838935223]
  - [0.006314972881543167, -0.018849485922810563, 0.9998023894740157, 0.026165491026715244]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [0.13288932347432716, -0.2892893914855217, -0.00029094085691318267, -0.00015674188472386888]
  distortion_model: radtan
  intrinsics: [1585.541452340946, 1584.2520429091494, 724.0871424593325, 948.5552906651193]
  resolution: [1440, 1920]
  rostopic: /cam0/image_raw
  timeshift_cam_imu: 0.001962675858041495
```
